version: "3.9"
services:
  web:
    container_name: web
    build:
      context: .
      secrets:
        - env
    expose:
      - "3000"
    environment:
      NODE_ENV: production
      # VIRTUAL_HOST: reddex.app,www.reddex.app
      # VIRTUAL_PORT: 3000
      # LETSENCRYPT_HOST: reddex.app,www.reddex.app
      # VIRTUAL_PATH: "/"

    command: npm run start
    restart: unless-stopped
networks:
  default:
    name: ioverland_v3
volumes:
  postgres_data:
secrets:
  env:
    file: .env
